### ISSUE TITLE
Multiple download

### ISSUE THREAD

**Issue by HexonDev** [Tyrrrz/YoutubeMusicDownloader#1]
HellO! How can I make multiple downloads at the same time? Thanks for your reply

**Comment by Tyrrrz** [comment]
It's in the [Usage examples](https://github.com/Tyrrrz/YoutubeMusicDownloader#usage-examples) although this program doesn't work atm since it uses an outdated version of YoutubeExplode.

**Comment by HexonDev** [comment]
Sorry, wrong category
